In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [2]:
from statsmodels.stats import diagnostic as diag
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [4]:
df = pd.read_excel('C:/Users/ABL2BAN/Desktop/Messers cuting tool/Economic Indicators For Model Building.xlsx',engine='openpyxl')
df = df.set_index('Date')

In [5]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [7]:
df.fillna(000, inplace=True)

In [8]:
df.isnull().sum()

Machine Sales in Pcs(X)     0
FoodAGRO\n(Rs. Mn)          0
Food products\n(Rs. Mn)     0
Consumer goods\n(Rs. Mn)    0
Electronics\n(Rs. Mn)       0
                           ..
Unnamed: 90                 0
Unnamed: 91                 0
Unnamed: 92                 0
Unnamed: 93                 0
Unnamed: 94                 0
Length: 94, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier  
from sklearn.metrics import accuracy_score

In [10]:
X = df.drop('Machine Sales in Pcs(X)', axis=1)  
y = df['Machine Sales in Pcs(X)']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [13]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.92

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
Lir_model = LinearRegression

In [16]:
X

,FoodAGRO\n(Rs. Mn),Food products\n(Rs. Mn),Consumer goods\n(Rs. Mn),Electronics\n(Rs. Mn),Wholesale & retail trading \n(Rs. Mn),Wholesale trading\n(Rs. Mn),Retail Trading\n(Rs. Mn),M1\nNarrow Money\n(Rs. Mn),M3\nBroad Money\n(Rs. Mn),BEI,...,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94
Date,,,,,,,,,,,,,,,,,,,,,
2009-09-01,1999267.4,1007509.7,1287064.1,227861.6,2915231.0,2176184.2,127533.8,13112940.0,51205350.0,107.20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2009-12-01,2235046.2,1166528.0,1411815.9,264305.1,3100963.5,2262351.6,148538.0,13309550.0,52453130.0,112.80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010-03-01,2312421.4,1187339.3,1457494.3,283397.5,2970817.7,2132925.4,143995.3,14892680.0,56026980.0,118.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010-06-01,2547990.5,1258511.1,1361595.5,254267.0,3445246.6,2489142.3,172392.5,14866500.0,57105800.0,115.91,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010-09-01,2999004.2,1508815.0,1628546.4,261094.8,3835419.2,2785845.6,207874.5,15198310.0,58992660.0,119.02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NaT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NaT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NaT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NaT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
y

Date
2009-09-01     3.0
2009-12-01     3.0
2010-03-01    11.0
2010-06-01    11.0
2010-09-01    11.0
              ...
NaT            0.0
NaT            0.0
NaT            0.0
NaT            0.0
NaT            0.0
Name: Machine Sales in Pcs(X), Length: 64, dtype: float64

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [19]:
X_train.shape

(51, 93)

In [20]:
X_test.shape

(13, 93)

In [21]:
y_test.shape

(13,)

In [22]:
y_train.shape

(51,)

In [23]:
X_train.head()

,FoodAGRO\n(Rs. Mn),Food products\n(Rs. Mn),Consumer goods\n(Rs. Mn),Electronics\n(Rs. Mn),Wholesale & retail trading \n(Rs. Mn),Wholesale trading\n(Rs. Mn),Retail Trading\n(Rs. Mn),M1\nNarrow Money\n(Rs. Mn),M3\nBroad Money\n(Rs. Mn),BEI,...,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94
Date,,,,,,,,,,,,,,,,,,,,,
2012-12-01,4349360.0,1931988.2,2737655.0,184496.3,2433076.5,1462948.4,282566.8,18128740.0,80336620.0,104.49,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2018-03-01,7725064.5,4228349.6,7840465.3,665076.6,4918548.9,1611451.0,1707960.2,32673313.0,139625865.0,110.40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022-03-01,11936483.8,8445862.8,12512217.2,1195656.4,18170334.8,9773974.5,4219468.2,53071250.0,204937290.0,111.53,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010-06-01,2547990.5,1258511.1,1361595.5,254267.0,3445246.6,2489142.3,172392.5,14866500.0,57105800.0,115.91,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-12-01,4741693.5,2045819.9,2798255.9,130296.1,1722439.7,865780.2,224477.9,19896860.0,92229920.0,99.30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
X_test.head()

,FoodAGRO\n(Rs. Mn),Food products\n(Rs. Mn),Consumer goods\n(Rs. Mn),Electronics\n(Rs. Mn),Wholesale & retail trading \n(Rs. Mn),Wholesale trading\n(Rs. Mn),Retail Trading\n(Rs. Mn),M1\nNarrow Money\n(Rs. Mn),M3\nBroad Money\n(Rs. Mn),BEI,...,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94
Date,,,,,,,,,,,,,,,,,,,,,
2022-09-01,14328941.2,9763403.2,14482751.0,1285797.7,23229379.8,13130584.6,4716686.9,52280400.0,210728960.0,106.74,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NaT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2009-09-01,1999267.4,1007509.7,1287064.1,227861.6,2915231.0,2176184.2,127533.8,13112940.0,51205350.0,107.20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-09-01,8047361.8,5638779.2,10283753.9,631090.3,6243668.9,2495187.2,2135228.0,43249744.2,177397645.3,100.60,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010-12-01,3053464.4,1582996.5,1606825.7,280455.7,3669257.3,2574019.3,185699.8,15917730.0,62251810.0,122.79,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
X = df.drop('Machine Sales in Pcs(X)', axis=1)  
y = df['Machine Sales in Pcs(X)']

In [26]:
y

Date
2009-09-01     3.0
2009-12-01     3.0
2010-03-01    11.0
2010-06-01    11.0
2010-09-01    11.0
              ...
NaT            0.0
NaT            0.0
NaT            0.0
NaT            0.0
NaT            0.0
Name: Machine Sales in Pcs(X), Length: 64, dtype: float64

In [27]:
Lir_model

sklearn.linear_model._base.LinearRegression

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the model
model = LinearRegression()

# Fit the model
model.fit(X_train, y_train)

LinearRegression()

In [29]:
coefficients = model.coef_
print("Coefficients:", coefficients)

Coefficients: [-1.33984350e-06  1.41981224e-07 -1.46957279e-06 -2.63160530e-05
 -4.13806577e-07 -8.48935338e-07  2.03198487e-05 -3.38475230e-07
 -6.75713926e-07  6.57081946e-08 -4.58954196e-07 -5.45253234e-07
  5.54719750e-08 -4.21763493e-07 -2.52194285e-07  8.65750197e-08
  1.16617768e-05  7.78069627e-07  2.93461190e-08 -5.84376167e-08
 -4.09213651e-04 -1.07623739e-07  1.08730528e-07 -3.76510807e-08
 -3.98379437e-07 -9.08779875e-08  6.90935201e-08 -6.45843446e-07
 -1.43488633e-05 -7.81273541e-05 -1.72808670e-06 -8.38790226e-06
 -1.37217529e-05  8.10307953e-06 -7.86330569e-06  3.62949793e-06
 -7.36714806e-07  1.63382284e-06 -5.68459426e-07  1.50385466e-04
  1.30346357e-04  1.28230365e-04 -1.56165094e-05 -1.42839903e-06
  1.64348462e-05 -1.09709246e-05 -2.35839827e-06  1.94079971e-05
  1.23753215e-05  3.96659984e-05  2.19310378e-05 -2.46976773e-05
 -4.81122697e-05  3.39574919e-05 -1.05413781e-05  5.84834422e-05
 -6.63890079e-05 -9.65588334e-05  2.53416952e-05  9.14438382e-06
  2.97113769e-05  2.25124258e-05 -6.63767213e-05  4.00530380e-05
 -1.53661837e-05  1.37544761e-05  6.98968470e-07 -4.61217320e-06
 -4.02033879e-06  1.19403375e-05 -1.45199334e-05 -2.47375628e-07
 -3.05636911e-05 -8.16433294e-06 -1.47631357e-05  1.57715338e-04
 -2.31400367e-06  3.69076797e-06  1.50051241e-05  7.03790140e-06
  4.90445104e-06  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00]

In [30]:
intercept = model.intercept_
print("Intercept:", intercept)

Intercept: 2.4229507289419416e-12

In [31]:
coefficients = model.coef_

In [32]:
for feature, coef in zip(X_train.columns, coefficients):
    print(f"Coefficient for {feature}: {coef}")

Coefficient for FoodAGRO
(Rs. Mn): -1.3398435027616524e-06
Coefficient for Food products
(Rs. Mn): 1.4198122414923444e-07
Coefficient for Consumer goods
(Rs. Mn): -1.4695727923838466e-06
Coefficient for Electronics
(Rs. Mn): -2.6316052959778307e-05
Coefficient for Wholesale & retail trading
(Rs. Mn): -4.138065773658706e-07
Coefficient for Wholesale trading
(Rs. Mn): -8.489353384998135e-07
Coefficient for Retail Trading
(Rs. Mn): 2.0319848661128168e-05
Coefficient for M1
Narrow Money
(Rs. Mn): -3.3847523029686933e-07
Coefficient for M3
Broad Money
(Rs. Mn): -6.757139262665389e-07
Coefficient for BEI: 6.57081946119734e-08
Coefficient for IIP: -4.589541955559308e-07
Coefficient for PMI: -5.452532339582038e-07
Coefficient for CC: 5.5471975008290994e-08
Coefficient for CPI: -4.2176349260520933e-07
Coefficient for WPI: -2.521942846657041e-07
Coefficient for CMR: 8.657501966104173e-08
Coefficient for Vloans
(Rs.Mn): 1.166177683416002e-05
Coefficient for Ind_freight: 7.780696266082408e-07
Coefficient for Repo Rate: 2.934611903651388e-08
Coefficient for Base Rate: -5.8437616721026864e-08
Coefficient for MGNREGS Employment : -0.00040921365073176406
Coefficient for Unemployment Rate: -1.0762373934103946e-07
Coefficient for House Price Index : All India: 1.0873052772524973e-07
Coefficient for Exchange Rate
INR vs USD: -3.7651080735304295e-08
Coefficient for Exchange Rate
INR vs Euro: -3.9837943676417705e-07
Coefficient for Petrol Rate: -9.087798754545058e-08
Coefficient for Diesel Rates: 6.909352014705519e-08
Coefficient for Crude Oil: -6.458434457823863e-07
Coefficient for Pig Iron Avg Cost: -1.4348863295071457e-05
Coefficient for Cu London Metal Exchange USD: -7.812735406666374e-05
Coefficient for Cemment Average wholesale Mumbai Rs/50Kg bag: -1.7280867019623594e-06
Coefficient for Au London Metal  Exchange USD: -8.38790226025111e-06
Coefficient for Infra Index: -1.3721752852983257e-05
Coefficient for COSPI
(Automobiles & Ancillaries Industry Index) : 8.103079533926259e-06
Coefficient for COSPI1 (Automotive Ancillaries): -7.863305687806125e-06
Coefficient for GDP
Rs. Mn
(Current): 3.6294979278044047e-06
Coefficient for GDP
YoY%
(Current): -7.367148060046326e-07
Coefficient for GDP
Rs. Mn
(Constant): 1.6338228386070003e-06
Coefficient for GDP
YoY%
(Constant): -5.684594263707527e-07
Coefficient for Per capita GDP : 0.00015038546553125987
Coefficient for Per capita GNI : 0.00013034635702484894
Coefficient for Per capita NNI : 0.00012823036501394803
Coefficient for Per capita PFCE : -1.5616509382946092e-05
Coefficient for IIP Growth YoY%: -1.4283990317772596e-06
Coefficient for GVA (Constant): 1.6434846226414732e-05
Coefficient for GVA Agri(Constant): -1.0970924631209663e-05
Coefficient for GVA
Indus(Constant): -2.358398270291807e-06
Coefficient for GVA
Mine(Constant): 1.9407997094921873e-05
Coefficient for GVA
Mfg(Constant): 1.2375321541821268e-05
Coefficient for GVA
Electricity(Constant): 3.9665998434942356e-05
Coefficient for GVA
Construct(Constant): 2.1931037795344373e-05
Coefficient for GVA
Services Total (Constant): -2.4697677293459094e-05
Coefficient for GVA
Trade(Constant): -4.811226972938755e-05
Coefficient for GVA
Real Estate(Constant): 3.395749190502278e-05
Coefficient for GVA
Social  and personal  services (Constant): -1.0541378136712185e-05
Coefficient for GVA (Current): 5.84834421545784e-05
Coefficient for GVA Agri(Current): -6.638900792346793e-05
Coefficient for GVA
Indus(Current): -9.655883337162542e-05
Coefficient for GVA
Mine(Current): 2.5341695210049237e-05
Coefficient for GVA
Mfg(Current): 9.144383815524169e-06
Coefficient for GVA
ele(Current): 2.9711376859773745e-05
Coefficient for GVA
Construction(Current): 2.251242581030009e-05
Coefficient for GVA
Services Total (Current): -6.637672128885261e-05
Coefficient for GVA
Trade(Current): 4.005303795691683e-05
Coefficient for GVA
Real Estate(Current): -1.5366183713034973e-05
Coefficient for GVA
Social  and personal  services (Current): 1.375447614722697e-05
Coefficient for Domestic cargo/freight handled
: 6.989684696167344e-07
Coefficient for MSP Kharif Season: -4.6121731954162014e-06
Coefficient for MSP Rabi Season: -4.020338790007601e-06
Coefficient for Total : 1.194033754782963e-05
Coefficient for Petro:crude&products : -1.4519933414844157e-05
Coefficient for Total Imports: -2.473756277888555e-07
Coefficient for Agri&allied&products : -3.056369105578067e-05
Coefficient for Ores & minerals : -8.164332936895418e-06
Coefficient for Mfg goods : -1.4763135703867391e-05
Coefficient for Mfg,goods Leather mfg: 0.00015771533833176536
Coefficient for Chem& related,products : -2.314003665360418e-06
Coefficient for Engineering goods : 3.6907679673304892e-06
Coefficient for Electronic goods : 1.5005124117013507e-05
Coefficient for Other mfg,goods : 7.0379014021721025e-06
Coefficient for Other commodities : 4.904451043464194e-06
Coefficient for Unnamed: 83: 0.0
Coefficient for Unnamed: 84: 0.0
Coefficient for Unnamed: 85: 0.0
Coefficient for Unnamed: 86: 0.0
Coefficient for Unnamed: 87: 0.0
Coefficient for Unnamed: 88: 0.0
Coefficient for Unnamed: 89: 0.0
Coefficient for Unnamed: 90: 0.0
Coefficient for Unnamed: 91: 0.0
Coefficient for Unnamed: 92: 0.0
Coefficient for Unnamed: 93: 0.0
Coefficient for Unnamed: 94: 0.0

In [33]:
r2_score = model.score(X_train, y_train)
print(f"R^2 Score on Training Set: {r2_score:.2f}")

R^2 Score on Training Set: 1.00

In [34]:
r2_score = model.score(X_test, y_test)
print(f"R^2 Score on Training Set: {r2_score:.2f}")

R^2 Score on Training Set: 0.69

In [35]:
# R^2 score on training data
train_score = model.score(X_train, y_train)
print(f"R^2 Score on Training Set: {train_score:.2f}")

# R^2 score on testing data
test_score = model.score(X_test, y_test)
print(f"R^2 Score on Testing Set: {test_score:.2f}")

R^2 Score on Training Set: 1.00
R^2 Score on Testing Set: 0.69

In [36]:
df.columns

Index(['Machine Sales in Pcs(X)', 'FoodAGRO\n(Rs. Mn)',
       'Food products\n(Rs. Mn)', 'Consumer goods\n(Rs. Mn)',
       'Electronics\n(Rs. Mn)', 'Wholesale & retail trading \n(Rs. Mn)',
       'Wholesale trading\n(Rs. Mn)', 'Retail Trading\n(Rs. Mn)',
       'M1\nNarrow Money\n(Rs. Mn)', 'M3\nBroad Money\n(Rs. Mn)', 'BEI', 'IIP',
       'PMI', 'CC', 'CPI', 'WPI', 'CMR', 'Vloans\n(Rs.Mn)', 'Ind_freight',
       'Repo Rate', 'Base Rate', 'MGNREGS Employment ', 'Unemployment Rate',
       'House Price Index : All India', 'Exchange Rate\nINR vs USD',
       'Exchange Rate\nINR vs Euro', 'Petrol Rate', 'Diesel Rates',
       'Crude Oil', 'Pig Iron Avg Cost', 'Cu London Metal Exchange USD',
       'Cemment Average wholesale Mumbai Rs/50Kg bag',
       'Au London Metal  Exchange USD', 'Infra Index',
       'COSPI\n(Automobiles & Ancillaries Industry Index) ',
       'COSPI1 (Automotive Ancillaries)', 'GDP \nRs. Mn\n(Current)',
       'GDP \nYoY%\n(Current)', 'GDP \nRs. Mn\n(Constant)',
       'GDP \nYoY%\n(Constant)', 'Per capita GDP ', 'Per capita GNI ',
       'Per capita NNI ', 'Per capita PFCE ', 'IIP Growth YoY%',
       'GVA (Constant)', 'GVA Agri(Constant)', 'GVA\nIndus(Constant)',
       'GVA \nMine(Constant)', 'GVA\nMfg(Constant)',
       'GVA\nElectricity(Constant)', 'GVA\nConstruct(Constant)',
       'GVA \nServices Total (Constant)', 'GVA\nTrade(Constant)',
       'GVA \nReal Estate(Constant)',
       'GVA\nSocial  and personal  services (Constant)', 'GVA (Current)',
       'GVA Agri(Current)', 'GVA\nIndus(Current)', 'GVA \nMine(Current)',
       'GVA\nMfg(Current)', 'GVA\nele(Current)', 'GVA\nConstruction(Current)',
       'GVA \nServices Total (Current)', 'GVA\nTrade(Current)',
       'GVA \nReal Estate(Current)',
       'GVA\nSocial  and personal  services (Current)',
       'Domestic cargo/freight handled \n', 'MSP Kharif Season',
       'MSP Rabi Season', 'Total ', 'Petro:crude&products ', 'Total Imports',
       'Agri&allied&products ', 'Ores & minerals ', 'Mfg goods ',
       'Mfg,goods Leather mfg', 'Chem& related,products ',
       'Engineering goods ', 'Electronic goods ', 'Other mfg,goods ',
       'Other commodities ', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85',
       'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89',
       'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93',
       'Unnamed: 94'],
      dtype='object')

In [69]:
df1 = ['Machine Sales in Pcs(X)', 'FoodAGRO\n(Rs. Mn)',  'Electronics\n(Rs. Mn)',  'BEI', 'Vloans\n(Rs.Mn)', 'Ind_freight', 'MGNREGS Employment ',  'House Price Index : All India', 
       'Exchange Rate\nINR vs Euro', 'Diesel Rates', 'Pig Iron Avg Cost',
       'Au London Metal  Exchange USD', 'Infra Index', 'COSPI\n(Automobiles & Ancillaries Industry Index) ', 'Per capita GDP ', 'MSP Rabi Season', 'Total ', 
       'Agri&allied&products ',  'Other commodities ', ]

In [70]:
df1 = df[df1]

In [71]:
# define two data frames one before the drop and one after the drop
#econ_df_before12 = econ_df_before1
#econ_df_before12 = econ_df_before1.drop(['Credit_CS'],axis=1)
df_before = df1
  
# the VFI does expect a constant term in the data, so we need to add one using the add_constant method
#X1 = sm.tools.add_constant(econ_df_before12)
X2 = sm.tools.add_constant(df_before)

# create the series for both
#series_before = pd.Series([variance_inflation_factor(X1.values, i) for i in range(X1.shape[1])], index=X1.columns)
series_after =  pd.Series([variance_inflation_factor(X2.values, i) for i in range(X2.shape[1])], index=X2.columns)

#display the s eries 
#print('DATA BEFORE')
#print('-'*100)
#with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    #print(series_before)

print('DATA BEFORE')
print('-'*100)
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(series_after)

DATA BEFORE
----------------------------------------------------------------------------------------------------

const                                                  10.631032
Machine Sales in Pcs(X)                                22.673948
FoodAGRO\n(Rs. Mn)                                    250.027015
Electronics\n(Rs. Mn)                                  60.129440
BEI                                                    24.511480
Vloans\n(Rs.Mn)                                        58.489148
Ind_freight                                            65.337466
MGNREGS Employment                                     59.351968
House Price Index : All India                         382.973457
Exchange Rate\nINR vs Euro                             85.571761
Diesel Rates                                          211.684168
Pig Iron Avg Cost                                      63.293786
Au London Metal  Exchange USD                          45.237218
Infra Index                                            66.781648
COSPI\n(Automobiles & Ancillaries Industry Index)     106.394343
Per capita GDP                                        372.486530
MSP Rabi Season                                       633.258164
Total                                                  42.315440
Agri&allied&products                                   39.132267
Other commodities                                       3.183416
dtype: float64

In [72]:
X = df_before.drop('Machine Sales in Pcs(X)', axis=1)  
y = df_before['Machine Sales in Pcs(X)']
 
# Split X and y into X_
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

# create a Linear Regression model object
regression_model = LinearRegression()

# pass through the X_train & y_train data set
regression_model.fit(X_train, y_train)

LinearRegression()

In [73]:
# Get multiple predictions
y_predict = regression_model.predict(X_test)
predict = regression_model.predict(X_train)
# Show the first 12 predictions
train_mape = ((abs((y_train-predict)/y_train)).mean())*100
test_mape = ((abs((y_test-y_predict)/y_test)).mean())*100
print("Train Mape in % is ...", train_mape)
print("Test Mape in % is ...", test_mape)

Train Mape in % is ... inf
Test Mape in % is ... inf

In [74]:
mod = sm.OLS(y_train,X_train).fit()
print(mod.summary())

                                   OLS Regression Results
============================================================================================
Dep. Variable:     Machine Sales in Pcs(X)   R-squared (uncentered):                   0.994
Model:                                 OLS   Adj. R-squared (uncentered):              0.990
Method:                      Least Squares   F-statistic:                              284.9
Date:                     Tue, 27 Aug 2024   Prob (F-statistic):                    5.31e-31
Time:                             10:34:56   Log-Likelihood:                         -97.558
No. Observations:                       51   AIC:                                      231.1
Df Residuals:                           33   BIC:                                      265.9
Df Model:                               18
Covariance Type:                 nonrobust
=====================================================================================================================
                                                        coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------
FoodAGRO
(Rs. Mn)                                  8.923e-07   1.11e-06      0.806      0.426   -1.36e-06    3.15e-06
Electronics
(Rs. Mn)                               2.684e-06   3.99e-06      0.673      0.505   -5.43e-06    1.08e-05
BEI                                                   0.0110      0.042      0.263      0.794      -0.074       0.097
Vloans
(Rs.Mn)                                    -2.964e-06   1.74e-06     -1.705      0.098    -6.5e-06    5.73e-07
Ind_freight                                           0.2039      0.063      3.259      0.003       0.077       0.331
MGNREGS Employment                                -4.389e-05    6.9e-05     -0.636      0.529      -0.000    9.65e-05
House Price Index : All India                         0.0365      0.062      0.590      0.559      -0.090       0.163
Exchange Rate
INR vs Euro                             0.2047      0.112      1.834      0.076      -0.022       0.432
Diesel Rates                                         -0.3778      0.167     -2.265      0.030      -0.717      -0.038
Pig Iron Avg Cost                                 -2.737e-05      0.000     -0.175      0.862      -0.000       0.000
Au London Metal  Exchange USD                         0.0089      0.003      3.519      0.001       0.004       0.014
Infra Index                                          -0.0056      0.002     -3.556      0.001      -0.009      -0.002
COSPI
(Automobiles & Ancillaries Industry Index)   9.851e-07   6.36e-07      1.549      0.131   -3.09e-07    2.28e-06
Per capita GDP                                    -1.958e-05   9.76e-05     -0.201      0.842      -0.000       0.000
MSP Rabi Season                                      -0.0038      0.014     -0.283      0.779      -0.031       0.024
Total                                              9.424e-07    5.1e-07      1.849      0.073   -9.48e-08    1.98e-06
Agri&allied&products                               -1.36e-06   9.12e-06     -0.149      0.882   -1.99e-05    1.72e-05
Other commodities                                 -1.414e-05   3.79e-06     -3.726      0.001   -2.19e-05   -6.42e-06
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   1.634
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.815
Skew:                           0.299   Prob(JB):                        0.665
Kurtosis:                       2.841   Cond. No.                     9.20e+06
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 9.2e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [65]:
from sklearn.preprocessing import MinMaxScaler
X1 = X
scaler = MinMaxScaler()
print(scaler.fit(X1))
MinMaxScaler()
print(scaler.data_max_)
X2 = scaler.transform(X1)

MinMaxScaler()
[1.88795120e+07 2.91954150e+06 5.91722100e+07 1.22790000e+02
 5.83297150e+06 1.45900000e+02 1.32991900e+05 3.13550000e+02
 9.00000000e+01 9.72500000e+01 6.80075250e+04 3.26720000e+03
 7.30340000e+03 2.13100997e+07 2.11725000e+05 2.12500000e+03
 1.50835467e+07 8.35551900e+05 7.15441000e+05]

In [66]:
from sklearn.preprocessing import MinMaxScaler
Y1 = y
scaler = MinMaxScaler()
print(scaler.fit(y))
MinMaxScaler()
print(scaler.data_max_)
Y2 = scaler.transform(y1)

ValueError: Expected 2D array, got 1D array instead:
array=[ 3.  3. 11. 11. 11. 11. 21. 21. 21. 21. 20. 20. 20. 20. 17. 17. 17. 17.
 18. 18. 18. 18. 22. 22. 22. 22. 23. 23. 23. 23. 28. 28. 28. 28. 29. 29.
 29. 29. 21. 21. 21. 21. 16. 16. 16. 16. 19. 19. 19. 19. 24. 24. 24. 24.
 25. 25. 25. 25.  0.  0.  0.  0.  0.  0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [67]:
# Split X and y into X_
X1_train, X1_test, y1_train, y1_test = train_test_split(X2, Y1, test_size=0.20, random_state=1)

# create a Linear Regression model object
regression_model = LinearRegression()

# pass through the X_train & y_train data set
regression_model.fit(X1_train, y1_train)

LinearRegression()

In [68]:
for feature, coef in zip(X_train.columns, coefficients):
    print(f"Coefficient for {feature}: {coef}")

Coefficient for FoodAGRO
(Rs. Mn): -1.3398435027616524e-06
Coefficient for Electronics
(Rs. Mn): 1.4198122414923444e-07
Coefficient for M1
Narrow Money
(Rs. Mn): -1.4695727923838466e-06
Coefficient for BEI: -2.6316052959778307e-05
Coefficient for Vloans
(Rs.Mn): -4.138065773658706e-07
Coefficient for Ind_freight: -8.489353384998135e-07
Coefficient for MGNREGS Employment : 2.0319848661128168e-05
Coefficient for House Price Index : All India: -3.3847523029686933e-07
Coefficient for Exchange Rate
INR vs Euro: -6.757139262665389e-07
Coefficient for Diesel Rates: 6.57081946119734e-08
Coefficient for Pig Iron Avg Cost: -4.589541955559308e-07
Coefficient for Au London Metal  Exchange USD: -5.452532339582038e-07
Coefficient for Infra Index: 5.5471975008290994e-08
Coefficient for COSPI
(Automobiles & Ancillaries Industry Index) : -4.2176349260520933e-07
Coefficient for Per capita GDP : -2.521942846657041e-07
Coefficient for MSP Rabi Season: 8.657501966104173e-08
Coefficient for Total : 1.166177683416002e-05
Coefficient for Agri&allied&products : 7.780696266082408e-07
Coefficient for Other commodities : 2.934611903651388e-08